### PR TITLE
Added solutions to questions 10.1 and 10.2

### PR DESCRIPTION
**Pull request by jumpmanmv**

### CODE REVIEW

**Review by KrishMunot — APPROVED** [review]

**Comment by gdhp** [comment]
Does 10.1 solution ever work? no crashes??

**Comment by jumpmanmv** [comment]
@gdhp Hello, the solution I wrote for question 10.1 works for any 2 integer arrays. I haven't encountered any errors or crashes. Can you describe the problem you're having in more detail?

**Comment by rafaelchen** [comment]
@jumpmanmv 
my two cents:
how about to use 
```
std::swap(arr[i], arr[cur_index]);
```
to replace the following lines:
```
std::string temp = arr[i];
arr[i] = arr[cur_index];
arr[cur_index] = temp;
```
it would be more clear.
Thanks.

**Comment by rafaelchen** [comment]
@jumpmanmv 
regarding the 10.1 solution, the line
```
int A[5] = {1, 3, 5, 7, 9};
```
it means the size of array A only is 5, however, the line
```
for (int a = 0; a < total_size; a++) {
        std::cout << A[a] << " ";
}
```
the index will over 5, it may cause issue (out of boundary)

**Comment by jumpmanmv** [comment]
@rafaelchen made the changes based on your suggestions and created a pull request. Thanks!

**Pull request merged**
